// Source of truth for the Scentrances catalogue.
// Prices are in PKR. Each perfume ships in three sizes (50ml / 30ml / 10ml travel).
// Prices come straight from the Signature Collection pricing sheet.
// Descriptions for Boom Boom and Deenar were written to match their imagery/notes.

const sizes = (p50, p30, p10) => [
  { size: '50ml', price: p50, stock: 40 },
  { size: '30ml', price: p30, stock: 40 },
  { size: '10ml', price: p10, stock: 60 },
];

export const products = [
  {
    slug: 'sea-view',
    name: 'Sea View',
    gender: 'men',
    family: 'Fresh / Aquatic',
    tagline: 'Ride the Wave. Own the Moment.',
    description:
      "Dive into an endless horizon with Sea View — a fresh, aquatic fragrance that captures the raw energy of the open ocean. Crafted for the modern man who moves with purpose and lives without limits, Sea View is a timeless expression of freedom, confidence, and cool sophistication. Each spray is a breath of crisp sea air on a sun-drenched shoreline.",
    notes_top: ['Spearmint', 'Green Nuances', 'Marine Accord (Calone)'],
    notes_mid: ['Jasmine', 'Geranium', 'Rosewood', 'Lavender'],
    notes_base: ['Musk', 'Oakmoss', 'Cedarwood', 'Amber'],
    personality:
      'The man who wears Sea View exudes effortless cool. He is athletic, self-assured, adventurous, and deeply magnetic. He commands attention without seeking it.',
    mood: '🌊 Fresh & Free | ☀️ Energetic | 💪 Confident | 🌿 Adventurous',
    season: 'Spring & Summer',
    best_time: 'Morning wear, daytime outings, gym sessions, office, casual weekends, beach trips.',
    image: 'sea-view.jpg',
    featured: 1,
    variants: sizes(1499, 899, 200),
  },
  {
    slug: 'royale-amber',
    name: 'Royale Amber',
    gender: 'men',
    family: 'Woody / Oriental',
    tagline: 'Power Refined. Prestige Defined.',
    description:
      "Step into a world of unapologetic luxury with Royale Amber — a bold, woody-oriental masterpiece built for the man who is always in command. With its warm amber heart and rich woody depth, this is a fragrance that lingers long after you've left the room. Royale Amber is not just a scent — it is a statement of authority, class, and unwavering masculinity.",
    notes_top: ['Bergamot', 'Pink Pepper', 'Cardamom', 'Grapefruit'],
    notes_mid: ['Vetiver', 'Patchouli', 'Oakmoss', 'Rose'],
    notes_base: ['Amber', 'Musk', 'Sandalwood', 'Cedarwood'],
    personality:
      'Royale Amber dresses a man in invisible armour. He is a natural leader — analytical, poised, and impeccably groomed. He speaks with conviction and walks with grace.',
    mood: '👔 Professional & Powerful | 🏆 Ambitious | 🖤 Sophisticated | 🌙 Commanding',
    season: 'Autumn & Winter',
    best_time: 'Office, business meetings, formal occasions, corporate events, evening wear.',
    image: 'royale-amber.jpg',
    featured: 1,
    variants: sizes(2299, 1099, 200),
  },
  {
    slug: 'scent-of-empire',
    name: 'Scent of Empire',
    gender: 'men',
    family: 'Fresh / Oriental',
    tagline: 'Conquer Every Room. Quietly.',
    description:
      "Scent of Empire is a majestic, fresh-oriental fragrance designed for those who were born to lead. Built on a foundation of crisp luminosity and warm depth, this scent carries the grandeur of ancient empires and the precision of modern power. When you wear Scent of Empire, you don't just walk into a room — you own it.",
    notes_top: ['Bergamot', 'Grapefruit', 'Lemon', 'Green Notes'],
    notes_mid: ['Sage', 'Vetiver', 'Iris', 'Pepper'],
    notes_base: ['Sandalwood', 'Musk', 'Ambergris', 'Cashmere Wood'],
    personality:
      "Those who wear Scent of Empire radiate quiet dominance. They are visionaries — worldly, polished, and deeply composed. Their confidence isn't loud; it's undeniable. They are the ones who shape history rather than merely witness it.",
    mood: '👑 Regal & Commanding | 🌍 Worldly | ✨ Prestigious | 🦅 Fearless',
    season: 'Autumn, Winter & Spring evenings',
    best_time: 'High-stakes meetings, luxury travel, formal dinners, important events.',
    image: 'scent-of-empire.jpg',
    featured: 1,
    variants: sizes(2599, 1299, 300),
  },
  {
    slug: 'fortune',
    name: 'Fortune',
    gender: 'men',
    family: 'Spicy / Woody',
    tagline: 'Bold Enough to Win. Sharp Enough to Stay.',
    description:
      "Fortune is an electrifying, spicy-woody fragrance that embodies ambition in its purest form. Charged with vibrant energy and masculine depth, it is the scent of a man who plays to win — in boardrooms, in life, and in love. Fortune doesn't whisper; it declares. Wear it when you're ready to take what's yours.",
    notes_top: ['Cardamom', 'Lemon Zest', 'Apple', 'Juniper Berry'],
    notes_mid: ['Violet', 'Tobacco', 'Cinnamon'],
    notes_base: ['Vetiver', 'Guaiac Wood', 'Suede', 'Amber'],
    personality:
      'The Fortune man is bold, charismatic, and unapologetically magnetic. He walks into every situation with a smirk and confidence that turns heads — daring, spontaneous, and unforgettable.',
    mood: '🎰 Daring & Bold | 🔥 Playful | 💫 Magnetic | 🌃 Night Energy',
    season: 'Spring & Summer evenings',
    best_time: 'Nights out, date nights, club events, social gatherings, special occasions.',
    image: 'fortune.jpg',
    featured: 0,
    variants: sizes(1699, 899, 200),
  },
  {
    slug: 'zahra',
    name: 'Zahra',
    gender: 'women',
    family: 'Floral',
    tagline: 'Bloom Freely. Shine Eternally.',
    description:
      "Zahra — meaning 'flower' in Arabic — is a radiant, feminine floral fragrance that celebrates the beauty of blossoming. Light, elegant, and joyfully alive, Zahra dances between a garden in full bloom and a woman in full confidence. It is the scent of femininity at its most vibrant: fresh, sweet, and deeply enchanting.",
    notes_top: ['Citrus', 'Red Berries', 'Rose', 'Peony'],
    notes_mid: ['Osmanthus', 'Violet', 'Jasmine', 'Lily'],
    notes_base: ['Sandalwood', 'Musk', 'Patchouli', 'Cedarwood'],
    personality:
      'She is graceful, warm, and radiantly alive. The woman who wears Zahra carries a natural elegance — always smiling, always glowing. People gravitate toward her for how she makes them feel.',
    mood: '🌸 Joyful & Radiant | 🌿 Refreshed | 💖 Romantic | 🦋 Free-Spirited',
    season: 'Spring & Summer',
    best_time: 'Daytime events, brunches, garden parties, casual outings, spring festivals.',
    image: 'zahra.jpg',
    featured: 1,
    variants: sizes(1899, 999, 200),
  },
  {
    slug: 'rose-mirage',
    name: 'Rose Mirage',
    gender: 'women',
    family: 'Floral / Powdery',
    tagline: 'Soft as Petals. Bold as Love.',
    description:
      "Rose Mirage is a tender, dreamy floral fragrance built around the timeless beauty of the rose. Delicate yet lasting, romantic yet modern — it is the scent of a quiet afternoon bathed in pink light. Rose Mirage envelops the wearer in a gentle, powdery embrace that feels both intimate and effortlessly stylish.",
    notes_top: ['Pink Pepper', 'Bergamot', 'Lychee'],
    notes_mid: ['Bulgarian Rose', 'Peony', 'Lily of the Valley', 'Magnolia'],
    notes_base: ['White Musk', 'Cedarwood', 'Sandalwood', 'Benzoin'],
    personality:
      'Rose Mirage is worn by a woman who is both tender and resilient — soft enough to love deeply and strong enough to stand alone. Her presence lingers like the last note of a song you can’t forget.',
    mood: '🌹 Romantic & Tender | 💗 Warm | 🌙 Dreamy | 🕊️ Peaceful',
    season: 'Spring & soft Summer evenings',
    best_time: 'Romantic evenings, date nights, weddings, intimate gatherings, gift occasions.',
    image: 'rose-mirage.jpg',
    featured: 0,
    variants: sizes(1999, 999, 200),
  },
  {
    slug: 'silver-soul',
    name: 'Silver Soul',
    gender: 'men',
    family: 'Fresh / Clean',
    tagline: 'Fresh. Clean. Undeniably You.',
    description:
      "Silver Soul is a crisp, clean fragrance that embodies pure freshness and effortless style. Light yet lasting, it is the everyday signature of a man who values simplicity and substance in equal measure. Versatile, wearable, and universally loved — the kind of scent you reach for morning after morning.",
    notes_top: ['Bergamot', 'Grapefruit', 'Eucalyptus', 'Green Apple'],
    notes_mid: ['Jasmine', 'Cedar', 'Lavender', 'Lily of the Valley'],
    notes_base: ['White Musk', 'Sandalwood', 'Tonka Bean', 'Oakmoss'],
    personality:
      "Silver Soul is for the dependable, grounded man. He doesn't chase trends — he sets them quietly. He is warm, genuine, and respected. Classic never goes out of style, and neither does he.",
    mood: '🌬️ Clean & Clear | 🤍 Minimalist | 🌤️ Calm | 💎 Timeless',
    season: 'Year-round (best Spring & Summer)',
    best_time: 'Everyday wear, morning routines, office, university, casual outings.',
    image: 'silver-soul.jpg',
    featured: 0,
    variants: sizes(1399, 799, 200),
  },
  {
    slug: 'bleu-dimpact',
    name: "Bleu D'Impact",
    gender: 'men',
    family: 'Fresh / Sporty',
    tagline: 'Move Fast. Leave a Mark.',
    description:
      "Bleu D'Impact is a high-energy, fresh-sporty fragrance designed for the man who never slows down. Bursting with vibrant citrus energy and grounded by a clean, woody base, it is the ideal companion for the active, ambitious man on the go. Gym, office, or everywhere in between — Bleu D'Impact keeps up.",
    notes_top: ['Grapefruit', 'Blood Orange', 'Petitgrain', 'Aldehydes'],
    notes_mid: ['Neroli', 'Pepper', 'Cedar'],
    notes_base: ['White Musk', 'Oakmoss', 'Vetiver', 'Sandalwood'],
    personality:
      'The man of Bleu D’Impact is driven, disciplined, and deeply attractive in his focused energy. Athletic and well-groomed, he effortlessly blends sport and sophistication.',
    mood: '⚡ Energetic & Dynamic | 🏃 Active | 🔵 Focused | 💪 Unstoppable',
    season: 'Spring & Summer',
    best_time: 'Morning workouts, active days, sports, casual professional settings, daytime socialising.',
    image: 'bleu-dimpact.jpg',
    featured: 1,
    variants: sizes(2399, 1199, 250),
  },
  {
    slug: 'midnight-alfa',
    name: 'Midnight Alfa',
    gender: 'men',
    family: 'Spicy / Woody',
    tagline: 'Dark. Intense. Impossible to Ignore.',
    description:
      "Midnight Alfa is a powerfully seductive, spicy-woody elixir that redefines masculine intensity. Rich, bold, and dangerously captivating, it is a fragrance for the man who embraces his depth and walks confidently into the unknown. Midnight Alfa doesn't ask for attention — it commands it.",
    notes_top: ['Bergamot', 'Spicy Pepper', 'Ginger'],
    notes_mid: ['Lavender', 'Sichuan Pepper', 'Cardamom'],
    notes_base: ['Amber', 'Cedarwood', 'Dark Musk', 'Labdanum', 'Elemi'],
    personality:
      'A man of mystery and substance wears Midnight Alfa. He is deeply self-aware, emotionally intelligent, and powerfully present. He says less and means more.',
    mood: '🌑 Dark & Mysterious | 🖤 Intense | 🔮 Deep & Brooding | 🐺 Wild',
    season: 'Autumn & Winter',
    best_time: 'Evening events, formal night occasions, date nights, intimate dinners, winter nights.',
    image: 'midnight-alfa.jpg',
    featured: 1,
    variants: sizes(4399, 1999, 450),
  },
  {
    slug: 'silent-breeze',
    name: 'Silent Breeze',
    gender: 'men',
    family: 'Fresh / Citrus',
    tagline: 'Effortless Freshness. Every Single Day.',
    description:
      "Silent Breeze is a light, clean, and beautifully refreshing fragrance that carries the quiet joy of a cool, breezy morning. Crisp and cheerful, it is designed for those who believe that simplicity is the highest form of elegance. It lifts your mood and refreshes your senses.",
    notes_top: ['Lemon', 'Bergamot', 'Grapefruit', 'Green Leaves'],
    notes_mid: ['Jasmine', 'White Musk', 'Lily'],
    notes_base: ['Cedarwood', 'Sandalwood', 'Oakmoss', 'Ambergris'],
    personality:
      'Silent Breeze belongs to the calm, composed, and quietly confident individual. Approachable, warm, and genuinely likeable — calm in every storm.',
    mood: '🌬️ Calm & Fresh | 🤍 Clean | 🌱 Uplifted | ☁️ Serene',
    season: 'All-season (best Spring & Summer)',
    best_time: 'Morning routines, office wear, outdoor activities, casual daily use.',
    image: 'silent-breeze.jpg',
    featured: 0,
    variants: sizes(1699, 899, 200),
  },
  {
    slug: 'crystal-bloom',
    name: 'Crystal Bloom',
    gender: 'women',
    family: 'Floral Oriental',
    tagline: 'Dark. Luminous. Impossibly Alluring.',
    description:
      "In a world of ordinary florals, Crystal Bloom dares to be extraordinary. Opening with a seductive spark of pepper and the exotic warmth of cardamom, it blossoms into a lush, velvety garden of gardenia, orange blossom and peony. The dry down reveals its true soul: warm sandalwood, rich amber and a deep, skin-fused musk that lingers long into the night. Crystal Bloom does not ask for your attention — it simply takes it.",
    notes_top: ['Black Pepper', 'Cardamom', 'Ginger Spice'],
    notes_mid: ['Gardenia', 'Orange Blossom', 'Peony', 'Orris'],
    notes_base: ['Sandalwood', 'Warm Amber', 'Dark Musk', 'Coconut Wood'],
    personality:
      'Crystal Bloom belongs to the woman who walks with purpose and mystery in equal measure. Elegant without effort. Dangerous without trying. The woman everyone steals glances at.',
    mood: '🖤 Mysterious & Deep | 💎 Glamorous | 🌹 Dark Romance | 🌙 Nocturnal Allure',
    season: 'Autumn & Winter',
    best_time: 'Formal events, gala dinners, cocktail parties, theatre nights, date nights, luxury travel.',
    image: 'crystal-bloom.jpg',
    featured: 1,
    variants: sizes(1899, 999, 200),
  },
  {
    slug: 'boom-boom',
    name: 'Boom Boom',
    gender: 'women',
    family: 'Fruity / Floral',
    tagline: 'Sweet Spark. Loud Heart.',
    description:
      "Boom Boom is a playful, fruity-floral burst of pure joy. It opens with a juicy explosion of pink grapefruit and exotic passion fruit, then melts into a flirtatious bouquet of lilac, peony and jasmine. A soft trail of vanilla and white musk leaves a sweet, irresistible memory wherever you go. Boom Boom is for the girl who walks in smiling and leaves everyone wanting more.",
    notes_top: ['Pink Grapefruit', 'Passion Fruit', 'Pink Pepper'],
    notes_mid: ['Lilac', 'Peony', 'Jasmine'],
    notes_base: ['Vanilla', 'White Musk', 'Cedarwood'],
    personality:
      'The Boom Boom girl is bubbly, flirtatious, and impossible to ignore. She is fun, spontaneous and full of life — the spark of every gathering.',
    mood: '💥 Playful & Fun | 🍑 Juicy | 💞 Flirty | 🎀 Sweet',
    season: 'Spring & Summer',
    best_time: 'Brunches, day dates, shopping days, parties, casual everyday glam.',
    image: 'boom-boom.jpg',
    featured: 0,
    variants: sizes(1799, 999, 200),
  },
  {
    slug: 'deenar',
    name: 'Deenar',
    gender: 'unisex',
    family: 'Oriental / Oud',
    tagline: 'Liquid Gold. Timeless Worth.',
    description:
      "Deenar is a regal oriental-oud fragrance inspired by the warmth of Arabian nights. A glowing saffron and bergamot opening gives way to a majestic heart of pure agarwood and Damask rose, wrapped in a base of amber, sandalwood and supple leather. Rich, opulent and unmistakably precious, Deenar is the scent of heritage, generosity and quiet power — a treasure worn on skin.",
    notes_top: ['Saffron', 'Bergamot', 'Pink Pepper'],
    notes_mid: ['Agarwood (Oud)', 'Damask Rose', 'Patchouli'],
    notes_base: ['Amber', 'Sandalwood', 'Leather', 'Musk'],
    personality:
      'The wearer of Deenar carries timeless dignity. Generous, grounded and commanding, they value tradition and craftsmanship — and their presence feels rich and reassuring.',
    mood: '👑 Regal & Warm | 🪔 Opulent | 🌹 Deep | 🕌 Timeless',
    season: 'Autumn & Winter',
    best_time: 'Weddings, festive nights, formal gatherings, special occasions, evening wear.',
    image: 'deenar.jpg',
    featured: 1,
    variants: sizes(3499, 1699, 350),
  },
];
